version: "3.9"

networks:
  k6:
  grafana:

services:
  health-web:
    build:
      context: "frontend"
    image: "localhost:7002/health-web:${IMAGE_TAG}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
    environment:
      - API_URL=${API_URL}
  health-api:
    build:
        context: "backend"
    image: "localhost:7002/health-api:${IMAGE_TAG}"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"