version: "3.9"

services:
  health-web:
    build:
      context: "frontend"
    image: "localhost:7002/web:${IMAGE_TAG}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
    environment:
      - API_URL=${API_URL}
  health-api:
    build:
        context: "backend"
    image: "localhost:7002/api:${IMAGE_TAG}"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"