version: "3.9"

networks:
  k6:
  grafana:

services:
  health-web:
    build:
      context: "frontend"
    image: "localhost:7002/health-web:${IMAGE_TAG}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
    environment:
      - API_URL=${API_URL}

  health-api:
    build:
        context: "backend"
    image: "localhost:7002/health-api:${IMAGE_TAG}"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"
# K6 stuff below here
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - /k6_loadtests:/k6_loadtests