version: "3.9"

networks:
  k6:
  grafana:
  health:

services:
  health-web:
    build:
      context: "frontend"
    image: "localhost:7002/health-web:${IMAGE_TAG}"
    networks:
      - health
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
    environment:
      - API_URL=${API_URL}

  health-api:
    build:
      context: "backend"
    image: "localhost:7002/health-api:${IMAGE_TAG}"
    networks:
      - health
    container_name: "${API_CONT_NAME}"
    environment:
      - DEBUG=socket*
    ports:
      - "${API_PORT}:3000"
    volumes:
      - /typeorm_config/ormconfig.json:/ormconfig.json

#  mysql:
#    image: mysql:8
#    container_name: "${DB_CONT_NAME}"
#    ports:
#      - 3306:3306
#    volumes:
#      - /db/mysql:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}

  # K6 stuff below here
  influxdb:
    container_name: "${INFLUXDB_CONT_NAME}"
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    container_name: "${GRAFANA_CONT_NAME}"
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./loadtests/dashboards:/var/lib/grafana/dashboards
      - ./loadtests/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./loadtests/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    container_name: "${K6_CONT_NAME}"
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./loadtests/scripts:/scripts
